### ISSUE TITLE
WELD-000321 when returning to a page which previously had a conversation

### ISSUE THREAD

**Issue by papegaaij** [42Lines/wicket-cdi#11]
When you try to restore a conversation which no longer exists, you get an exception 'WELD-000321 No conversation found to restore for id x'. This can happen, for example, when using the back button in the browser, but also when creating a link to a previous page in the page store. There seems to be no way to determine if a conversation with a given id exists, therefore I think the solution is to simply catch the NonexistentConversationException when calling 'activate'.

**Comment by ivaynberg** [comment]
i dont think its ok to just swallow the exception...

the page that expects a conversation is now running outside a conversational context - which will cause more errors later....

**Comment by papegaaij** [comment]
I'm not sure what's the best way to handle this. The problem is the exception occurs at quite a difficult location. Perhaps it should be possible to handle this in a way similar to expired pages? For us, simply catching and ignoring the exception works fine for now, but I see how this can cause other problems.

At the moment we use conversations to implement a workflow. Most of the pages in our application can be used as part of a workflow. When a workflow is started, we begin a long-running conversation. At the end of the workflow, the conversation is ended. Pages visited during the workflow can be revisited using the back-button, our through a history sidebar panel. These pages will work fine without the workflow being active. They will function as if they were opened via the menu.

In the future, we plan on using conversations for multi-page wizards. For these, the conversations are not optional. Trying to reopen one of these pages with no active conversation should fail, and probably reset the wizard to the first page.

To handle the NonexistentConversationException in such a way, I think the exception should be wrapped in a Wicket-specific exception to allow access to the page/handler for which the exception occurred. This would allow us to choose the destination to redirect to after the exception.

If you want, I can try to create a patch for this tomorrow. We use wicket-cdi in production now, and require this to be fixed properly, so I can spend some to time to come up with a good fix.

**Comment by ivaynberg** [comment]
yes, i think throwing a well-known exception is the best path forward. one thing to make sure is that since we throw an exception from inside a listener it is still processed by irequestcyclelistener#onexception()
